/**
 * @file This is the root component of the application.
 * It manages the overall application state, such as login status and the current view,
 * and acts as a router to render the correct component based on the user's navigation.
 * It also wraps the entire application in necessary context providers (Theme, Radio).
 */

import React, { useState, useEffect } from 'react';
import { LoginScreen } from './components/LoginScreen';
import { Studio } from './components/Studio';
import { Radio } from './components/Radio';
import { SongSubmission } from './components/SongSubmission';
import { SongLibrary } from './components/SongLibrary';
import { Leaderboard } from './components/Leaderboard';
import { Graveyard } from './components/Graveyard';
import { AlbumCoverGenerator } from './components/AlbumCoverGenerator';
import { MusicVideoGenerator } from './components/MusicVideoGenerator';
import { Gallery } from './components/Gallery';
import { Profile as ProfilePage } from './components/Profile';
import { PrivacyPolicy } from './components/PrivacyPolicy';
import { Loader } from './components/Loader';
import { AudioVisualizer } from './components/AudioVisualizer';
import { Ticker } from './components/Ticker';
import { DjTranscript } from './components/DjTranscript';
import { ThemeProvider } from './contexts/ThemeContext';
import { RadioProvider } from './contexts/AudioPlayerContext';
import { supabase } from './services/supabaseClient';
import { getUserSongs, uploadAudioFile, addSongToDatabase, getAllSongs } from './services/supabaseSongService';
import type { View, GalleryItem, Song, Session, Profile } from './types';

const App: React.FC = () => {
  // Supabase is now guaranteed to be configured via fallback values in supabaseClient.ts.
  // The explicit configuration check that showed an error screen is no longer needed.

  // State to track the user's Supabase session.
  const [session, setSession] = useState<Session | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  // State to manage loading while checking for an existing session.
  const [loading, setLoading] = useState(true);
  // Force API key to be ready to bypass the selector.
  const [apiKeyReady] = useState(true);
  const [showPrivacyPolicy, setShowPrivacyPolicy] = useState(false);
  // State to manage which view/page is currently active. Defaults to the studio dashboard.
  const [currentView, setCurrentView] = useState<View>('studio');
  // State to store items generated by the user (videos, album covers) for the gallery.
  const [galleryItems, setGalleryItems] = useState<GalleryItem[]>([]);
  // State to store all songs submitted by the user.
  const [songLibrary, setSongLibrary] = useState<Song[]>([]);
  // State to store ALL songs for the radio (global pool).
  const [globalSongPool, setGlobalSongPool] = useState<Song[]>([]);

  // Effect to handle Supabase authentication and data fetching, dependent on the API key being ready.
  useEffect(() => {
    // The supabase object from supabaseClient is now guaranteed to be initialized.
    setLoading(true); // Start loading for auth check

    const fetchInitialData = async (session: Session | null) => {
      console.log("🔄 App: fetchInitialData started", { session: session?.user?.id });
      setSession(session);
      try {
        if (session) {
          console.log("🔄 App: Fetching profile for user:", session.user.id);

          // Create a promise that rejects after 5 seconds
          const timeoutPromise = new Promise((_, reject) =>
            setTimeout(() => reject(new Error('Profile fetch timed out')), 5000)
          );

          // Race the fetch against the timeout
          const fetchPromise = supabase
            .from('profiles')
            .select('*')
            .eq('user_id', session.user.id)
            .single();

          let profileResult;
          try {
            profileResult = await Promise.race([fetchPromise, timeoutPromise]) as any;
          } catch (e) {
            console.error("❌ App: Profile fetch timed out or failed", e);
            throw e; // Re-throw to catch block
          }

          const { data: profileData, error: profileError } = profileResult;

          if (profileError) console.error("❌ App: Profile fetch error", profileError);
          setProfile(profileData);

          // Fetch the user's persisted song library from the database.
          console.log("🔄 App: Fetching user songs...");
          const userSongs = await getUserSongs(session.user.id);
          console.log(`✅ App: User songs fetched: ${userSongs.length}`);
          setSongLibrary(userSongs);

          // Fetch ALL songs for the radio with retry logic.
          console.log("🔄 App: Fetching global song pool...");
          let allSongs = await getAllSongs();

          // Retry up to 3 times if pool is empty (could be cold start or network blip)
          let retries = 0;
          while (allSongs.length === 0 && retries < 3) {
            console.warn(`⚠️ App: Global pool empty. Retrying (${retries + 1}/3)...`);
            await new Promise(resolve => setTimeout(resolve, 2000));
            allSongs = await getAllSongs();
            retries++;
          }

          console.log(`✅ App: Global pool fetched: ${allSongs.length}`);
          setGlobalSongPool(allSongs);
        } else {
          setProfile(null);
          setSongLibrary([]); // Clear library on logout.
          setGlobalSongPool([]);
        }
      } catch (error) {
        console.error('❌ App: Error loading initial data:', error);
        // Continue anyway - don't block the UI
      } finally {
        console.log("✅ App: fetchInitialData complete. Setting loading=false.");
        setLoading(false);
      }
    };

    supabase.auth.getSession().then(({ data: { session } }) => {
      fetchInitialData(session);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      async (event, session) => {
        // Ignore the initial session event as it is handled by getSession() above.
        // This prevents a double-fetch race condition that can get stuck in loading.
        if (event === 'INITIAL_SESSION') return;

        setLoading(true);
        await fetchInitialData(session);
      }
    );

    return () => subscription.unsubscribe();
  }, [apiKeyReady]); // This effect re-runs when the API key becomes ready.


  // Handler to change the current view.
  const handleNavigate = (view: View) => {
    setCurrentView(view);
  };

  // Handler for Admin Bypass Login (God Mode)
  const handleAdminLogin = () => {
    const mockUser = {
      id: 'god-mode-admin',
      email: 'god@clubyouniverse.live',
      app_metadata: {},
      user_metadata: {},
      aud: 'authenticated',
      created_at: new Date().toISOString(),
      role: 'authenticated'
    };

    const mockSession = {
      access_token: 'god-token',
      token_type: 'bearer',
      expires_in: 3600,
      refresh_token: 'god-refresh-token',
      user: mockUser
    } as any;

    const mockProfile: Profile = {
      user_id: 'god-mode-admin',
      name: 'The Creator',
      is_premium: true,
      is_artist: true,
      is_admin: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      stats: { plays: 999999, uploads: 999, votes_cast: 999, graveyard_count: 0 }
    };

    setSession(mockSession);
    setProfile(mockProfile);
    setSongLibrary([]); // Start clean or load default
    setGlobalSongPool([]); // Start clean
  };

  /**
   * Adds a newly created item to the gallery.
   * Prevents adding duplicate items based on the item's URL.
   * @param item - The gallery item to add (without an ID).
   */
  const addGalleryItem = (item: Omit<GalleryItem, 'id'>) => {
    // Avoid adding duplicates if user navigates back and forth
    if (galleryItems.some(existing => existing.url === item.url)) {
      return;
    }
    // Adds the new item to the beginning of the gallery array with a unique ID.
    setGalleryItems(prev => [{ ...item, id: Date.now().toString(), user_id: session?.user.id, created_at: new Date().toISOString() }, ...prev]);
  };

  /**
   * Handles the full song submission process:
   * 1. Uploads the audio file to Supabase Storage.
   * 2. Inserts the song metadata into the Supabase database.
   * 3. Updates the local React state to reflect the new song immediately.
   * @param songDetails - The details of the submitted song.
   */
  const addSongToLibrary = async (songDetails: { title: string; artist: string; audioFile: File; durationSec: number; source?: 'suno' | 'producer.ai' | 'mubert' | 'upload' }) => {
    if (!session?.user) {
      throw new Error("You must be logged in to submit a song.");
    }

    // 1. Upload audio file to Supabase Storage.
    const audioUrl = await uploadAudioFile(songDetails.audioFile, session.user.id);

    // 2. Prepare song metadata for database insertion.
    const newSongData: Omit<Song, 'id' | 'createdAt' | 'lastPlayedAt'> = {
      uploaderId: session.user.id,
      title: songDetails.title,
      artistName: songDetails.artist,
      source: songDetails.source || 'upload',
      audioUrl: audioUrl,
      coverArtUrl: `https://picsum.photos/seed/${Date.now()}/400`, // Generate a random placeholder cover
      durationSec: Math.round(songDetails.durationSec), // Round to integer for DB
      stars: 5, // All new songs start with 5 stars
      boxRoundsSeen: 0,
      boxRoundsLost: 0,
      boxAppearanceCount: 0,
      status: 'pool',
      playCount: 0,
      upvotes: 0,
      downvotes: 0,
    };

    // 3. Add song metadata to Supabase database.
    const savedSong = await addSongToDatabase(newSongData);

    // 4. Update local React state to show the new song immediately, placing it at the top of the list.
    setSongLibrary(prev => [savedSong, ...prev]);
    setGlobalSongPool(prev => [savedSong, ...prev]); // Also add to global pool
  };




  // The main render method
  return (
    <ThemeProvider>
      <RadioProvider>
        <AudioVisualizer />
        <div className="h-screen relative z-10 flex flex-col">
          <main className="flex-grow flex flex-col p-4 sm:p-8 min-h-0">
            {showPrivacyPolicy ? (
              <PrivacyPolicy onBack={() => setShowPrivacyPolicy(false)} />
            ) : loading ? (
              <div className="flex-grow flex items-center justify-center">
                <Loader message="Connecting to the studio..." />
              </div>
            ) : !session || !profile ? (
              <LoginScreen onShowPrivacy={() => setShowPrivacyPolicy(true)} onAdminLogin={handleAdminLogin} />
            ) : !profile.name ? (
              <ProfilePage onNavigate={handleNavigate} profile={profile} session={session} galleryItems={galleryItems} songs={songLibrary} onShowPrivacy={() => setShowPrivacyPolicy(true)} />
            ) : (
              <>
                {/* Radio is ALWAYS mounted and playing in background */}
                <div className={currentView === 'radio' ? 'flex flex-col flex-grow min-h-0' : 'hidden'}>
                  <Radio onNavigate={handleNavigate} songs={globalSongPool} profile={profile} setProfile={setProfile} />
                </div>

                {/* Other views render conditionally */}
                {currentView === 'studio' && (
                  <Studio onNavigate={handleNavigate} profile={profile} />
                )}
                {currentView === 'song-submission' && (
                  <SongSubmission onBackToStudio={() => handleNavigate('studio')} onSongSubmitted={addSongToLibrary} profile={profile} />
                )}
                {currentView === 'song-library' && (
                  <SongLibrary songs={songLibrary.filter(s => s.uploaderId === session.user.id)} onBackToStudio={() => handleNavigate('studio')} onNavigate={handleNavigate} />
                )}
                {currentView === 'leaderboard' && (
                  <Leaderboard onBackToStudio={() => handleNavigate('studio')} songs={songLibrary} />
                )}
                {currentView === 'graveyard' && (
                  <Graveyard onBackToStudio={() => handleNavigate('studio')} songs={songLibrary} />
                )}
                {currentView === 'album-cover' && (
                  <AlbumCoverGenerator onBackToStudio={() => handleNavigate('studio')} onCreationComplete={addGalleryItem} />
                )}
                {currentView === 'music-video' && (
                  <MusicVideoGenerator onBackToStudio={() => handleNavigate('studio')} onCreationComplete={addGalleryItem} onSongSubmitted={addSongToLibrary} />
                )}
                {currentView === 'gallery' && (
                  <Gallery items={galleryItems} onBackToStudio={() => handleNavigate('studio')} />
                )}
                {currentView === 'profile' && (
                  <ProfilePage onNavigate={handleNavigate} profile={profile} session={session} galleryItems={galleryItems} songs={songLibrary} onShowPrivacy={() => setShowPrivacyPolicy(true)} />
                )}
              </>
            )}
          </main>
          {/* Ticker only shows when viewing Radio */}
          {session && currentView === 'radio' && <Ticker />}
        </div>
        <DjTranscript />
      </RadioProvider>
    </ThemeProvider>
  );
};

export default App;